include: _default_template_yaml
task: mvbench_episodic_reasoning
dataset_name: episodic_reasoning
dataset_kwargs:
  data_files:
    train: ${MVBENCH_DATA_ROOT}/json/episodic_reasoning.json
test_split: train
doc_to_visual: !function utils.mvbench_doc_to_visual
  
lmms_eval_specific_kwargs:
  default:
    sub_task: episodic_reasoning
    post_prompt: "Only give the best option.\n"
