include: _default_template_yaml
task: mvbench_unexpected_action
dataset_name: unexpected_action
dataset_kwargs:
  data_files:
    train: ${MVBENCH_DATA_ROOT}/json/unexpected_action.json
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: unexpected_action
    post_prompt: "Only give the best option.\n"
